{{/*
Deployment template.
This template takes an array of values:
- the top context
- the deployment values
- optional template name of the overrides
*/}}
{{- define "common.deployment" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.deployment.tpl") -}}
{{- else -}}
{{- template "common.deployment.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.deployment.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args | default (list $top.Values) -}}
{{- $deployment := dict -}}
{{- range $values := $args -}}
{{- $deployment = $deployment | merge $values -}}
{{- end -}}
{{- $autoscaler := $deployment.autoscaler | default (dict) -}}
{{- $fullName := include "common.fullname" $top -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" . | nindent 2 }}
spec:
  {{- if not $autoscaler.enabled }}
  replicas: {{ $top.Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" $top | quote }}
      containers:
      - {{- include "common.container" . | nindent 8 }}
      {{- with $deployment.podSecurityContext }}
      securityContext:
        {{- toYaml $deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with $deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
