{{/*
Ingress template.
This template takes an array of values:
- the top context
- the ingress values
- the service values
- optional template name of the overrides

# Example values.yaml
ingress:
  enabled: true
  name: ingress
  rules:
  - host: example.com
  - path: /
  - host: example.com
    path: /foo
    service:
      name: myservice1
      port: http

service:
  type: ClusterIP
  name: service
  ports:
  - port: 1234
    targetPort: 1234
    protocol: tcp
    name: http
*/}}
{{- define "common.ingress" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.ingress.tpl") -}}
{{- else -}}
{{- template "common.ingress.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.ingress.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- $service  := last     $args | default (dict) -}}
{{- $args     := initial  $args -}}
{{- $ingress  := dict -}}
{{- range $values := compact $args -}}
{{- $ingress   = $ingress | merge $values -}}
{{- end -}}
{{- if $ingress.enabled -}}
{{- if semverCompare ">=1.14-0" $top.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- include "common.metadata" . | nindent 2 }}
spec:
  rules:
  {{- range $rule := $ingress.rules }}
  {{- $service := $rule.service | default $service }}
  {{- $port := $service.ports | default (list) }}
  {{- $port := first $port | default (dict) }}
  {{- $port := $port.name | default $port.port | default $service.port | default 80 }}
  {{- with $rule.host }}
  - host: {{ . | quote }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: {{ $rule.path | default "/" | quote }}
        backend:
          {{- with $service.name }}
          serviceName: "{{ include "common.fullname" $top }}-{{ . }}"
          {{- else }}
          serviceName: {{ include "common.fullname" $top | quote }}
          {{- end }}
          servicePort: {{ $port }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- toYaml $ingress.tls | nindent 4 }}
  {{- end -}}
{{/*
*/}}
{{- end -}}
{{- end -}}
